### ISSUE TITLE
Same quantities are not comparable

### ISSUE THREAD

**Issue by Azbesciak** [unitsofmeasurement/uom-systems#140]
Hello,
I just upgraded from 0.8 to 1.0, and have some problem with quantities (it occured also before, but without exception).
Lets consider following code:
````java
import org.junit.jupiter.api.Test;
import tec.uom.se.ComparableQuantity;
import tec.uom.se.quantity.Quantities;

import javax.measure.quantity.Speed;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static tec.uom.se.unit.Units.KILOMETRE_PER_HOUR;

class FailTest {
    @Test()
    void test() {
        var quantity = (ComparableQuantity<Speed>) Quantities.getQuantity("100 km/h");
        var speedFromInt = Quantities.getQuantity(100, KILOMETRE_PER_HOUR);
        assertTrue(quantity.isEquivalentTo(speedFromInt));
    }
}
````
This should pass, but it doesn't. It may be connected with 
https://github.com/unitsofmeasurement/uom-systems/issues/132 - in runtime I also receive following exception:
````
javax.measure.UnconvertibleException: javax.measure.IncommensurableException: km/h is not compatible with km/h
	at tec.uom.se.AbstractUnit.getConverterTo(AbstractUnit.java:296) ~[uom-se-1.0.10.jar:na]
	at tec.uom.se.AbstractQuantity.to(AbstractQuantity.java:181) ~[uom-se-1.0.10.jar:na]
	at tec.uom.se.AbstractQuantity.to(AbstractQuantity.java:110) ~[uom-se-1.0.10.jar:na]
````
And indeed - during debug I get something like comparing units `[L]/[T]` with `[T]/([L]*[M])`:
![image](https://user-images.githubusercontent.com/17334466/58469887-c4bb2580-8140-11e9-82d2-24934005cbfd.png)

**Comment by keilw** [comment]
Does this problem still happen in 2.0.1 or above?
