### ISSUE TITLE
NoClassDefFoundError on API 23 and lower

### ISSUE THREAD

**Issue by PierreNomade** [unitsofmeasurement/uom-systems#148]
Hi all,

We are using ucum library on an Android project. 
But it appears that we can't start our app on API 23 and lower.

When we try it, we got this error : 

        java.lang.NoClassDefFoundError: tec.uom.se.function.RationalConverter
             at tec.uom.se.AbstractUnit.divide(AbstractUnit.java:426)
             at tec.uom.se.AbstractUnit.divide(AbstractUnit.java:69)
             at tec.uom.se.unit.Units.<clinit>(Units.java:172)

Here is our gradle dependencies : 

    implementation 'systems.uom:systems-quantity:1.0'
    implementation 'systems.uom:systems-common-java8:1.0'
    implementation 'systems.uom:systems-unicode-java8:1.0'
    implementation 'systems.uom:systems-ucum-java8:1.0'

Works perfectly on API 24 and higher. 
Do you have any ideas of what could be the problem ?

Thank you !

**Comment by keilw** [comment]
On Android, that is an interesting question, do you try using it with Java or Kotlin? Possible that API 23 is not Java 8 compatible yet, then it would explain why.

**Comment by PierreNomade** [comment]
Thank you for the answer.

We are using Java.

Yes it seems that the problem is Java 8.
But is there a workaround to use ucum on API 23 and lower ?

**Comment by keilw** [comment]
I'm afraid UCUM was not done with the RI of JSR 363. I am not sure what the exact reason was, but I believe some of the classes made use of Java SE 8 right from the start. I can't say if that was ever used on Android, but [Eclipse UOMo](https://www.eclipse.org/uomo/download.php) including version 0.7 offers a UCUM module with "late binding" so it uses the full ucum-essence.xml file with the whole UCUM spec but some operations have less compile-time type-safety. Would that help your use case? We have not fully mavenized UOMo 0.7 or above, not sure, if that's a problem e.g. if you build with Gradle?
