### ISSUE TITLE
UCUMFormatter fails to parse CLDR.LITER_PER_100KILOMETRES correctly

### ISSUE THREAD

**Issue by feluso** [unitsofmeasurement/uom-systems#190]
```    
@Test
    void testRoundTripUCUMCSCLDRLiterPer100KM()
    {
        final String formatted = UCUMFormat.getInstance(UCUMFormat.Variant.CASE_SENSITIVE).format(systems.uom.unicode.CLDR.LITER_PER_100KILOMETERS);
        final Unit<? extends Quantity<?>> parsedUnit = UCUMFormat.getInstance(UCUMFormat.Variant.CASE_SENSITIVE).parse(formatted);
        System.out.print(parsedUnit);
    }
```

This test would fail with the following error: 

```
systems.uom.ucum.internal.format.TokenException
	at systems.uom.ucum.internal.format.UCUMFormatParser.SimpleUnit(UCUMFormatParser.java:207)
	at systems.uom.ucum.internal.format.UCUMFormatParser.Annotatable(UCUMFormatParser.java:180)
	at systems.uom.ucum.internal.format.UCUMFormatParser.Component(UCUMFormatParser.java:122)
	at systems.uom.ucum.internal.format.UCUMFormatParser.Term(UCUMFormatParser.java:77)
	at systems.uom.ucum.internal.format.UCUMFormatParser.parseUnit(UCUMFormatParser.java:67)
	at systems.uom.ucum.format.UCUMFormat$Parsing.parse(UCUMFormat.java:508)
	at systems.uom.ucum.format.UCUMFormat$Parsing.parse(UCUMFormat.java:526)
```

Upon closer inspection using a debugger, we can see the values in `UCUMFormatParser`

![imagen](https://user-images.githubusercontent.com/19785860/120807402-31473700-c548-11eb-8544-ee4c7a7946bb.png)

It seems the reason it fails it's because it parses `100` as `h` from `HECTO` but as this was already a `km`, the prefix only catches the `h` and not the `k` from `KILO` which causes it to be unable to recover the `m` unit from the `symbols` map, get a `null` instead and throw a `TokenException`

**Comment by keilw** [comment]
Thanks @feluso for pointing that out. HECTO and KILO should not be chained, in fact ICU4J (which is closely matched by the Unicode module here) defines in [MeasureUnit.Complexity](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/util/MeasureUnit.Complexity.html), that the recently declared [MeasureUnit.MeasurePrefix](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/util/MeasureUnit.MeasurePrefix.html) must not apply to `COMPOUND` units like meter-per-second, kilowatt-hour, kilogram-meter-per-square-second, etc.

**Comment by feluso** [comment]
thanks for the explanation, that makes sense, the constraints seem appropiate, and regarding #177 while similar, this seems (as the replies suggest) that it's more over the fact they seem to be flipped, as noted in tech.units.indriya.AbstractUnit:406: 

![imagen](https://user-images.githubusercontent.com/19785860/120993683-13feac80-c784-11eb-80df-7a68c6f0d2ea.png)

**Comment by keilw** [comment]
UCUMFormat is not intended to be used outside the UCUM system. With Unicode or other systems defined here please use SimpleUnitFormat or EBNFUnitFormat.
