### ISSUE TITLE
Parse error when trying to parse bit and byte

### ISSUE THREAD

**Issue by zifnab87** [unitsofmeasurement/uom-systems#51]
I am trying to parse "bit" and "byte" units and I can't make them work:
```
        UnitFormat unitFormat = SimpleUnitFormat.getInstance();
        Unit<Information> bit = unitFormat.parse("bit").asType(Information.class);
        System.out.println(bit);
```

```
        UnitFormat unitFormat = SimpleUnitFormat.getInstance();
        Unit<Information> byteU = unitFormat.parse("byte").asType(Information.class);
        System.out.println(byteU);
```

> Exception in thread "main" javax.measure.format.ParserException: Parse Error
> 	at tec.uom.se.format.SimpleUnitFormat$DefaultFormat.check(SimpleUnitFormat.java:561)
> 	at tec.uom.se.format.SimpleUnitFormat$DefaultFormat.parseSingleUnit(SimpleUnitFormat.java:414)
> 	at tec.uom.se.format.SimpleUnitFormat$DefaultFormat.parseProductUnit(SimpleUnitFormat.java:425)
> 	at tec.uom.se.format.SimpleUnitFormat.parseObject(SimpleUnitFormat.java:269)
> 	at tec.uom.se.format.SimpleUnitFormat$DefaultFormat.parse(SimpleUnitFormat.java:765)
> 	at tec.uom.se.format.SimpleUnitFormat$DefaultFormat.parse(SimpleUnitFormat.java:760)
> 	at tec.uom.se.format.SimpleUnitFormat$DefaultFormat.parse(SimpleUnitFormat.java:751)
> 	at testbed.TestBed.main(TestBed.java:37)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

I am using those maven dependencies:

```
        <dependency>
            <groupId>javax.measure</groupId>
            <artifactId>unit-api</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>tec.uom</groupId>
            <artifactId>uom-se</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>systems.uom</groupId>
            <artifactId>systems-common</artifactId>
            <version>0.6-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>systems.uom</groupId>
            <artifactId>systems-quantity</artifactId>
            <version>0.6-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>systems.uom</groupId>
            <artifactId>systems-unicode</artifactId>
            <version>0.6-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>systems.uom</groupId>
            <artifactId>systems-parent</artifactId>
            <version>0.6-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>javax.measure</groupId>
            <artifactId>unit-api</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>tec.uom</groupId>
            <artifactId>uom-se</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>systems.uom</groupId>
            <artifactId>systems-common</artifactId>
            <version>0.6-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>systems.uom</groupId>
            <artifactId>systems-quantity</artifactId>
            <version>0.6-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>systems.uom</groupId>
            <artifactId>systems-unicode</artifactId>
            <version>0.6-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>systems.uom</groupId>
            <artifactId>systems-parent</artifactId>
            <version>0.6-SNAPSHOT</version>
        </dependency>
```
I am not sure if I need to register the systems some how or just by including the jars I am good to go.
Thanks :)

**Comment by keilw** [comment]
Please check out https://github.com/unitsofmeasurement/uom-demos/blob/master/console/systems/unicode/src/main/java/tec/uom/demo/systems/unicode/CLDRFormatDemo.java and https://github.com/unitsofmeasurement/uom-demos/blob/master/console/systems/unicode-java8/src/main/java/tec/uom/demo/systems/unicode/CLDRFormatDemo.java demonstrating it's both working for `bit` and `byte` now. Note, to enable registration of a new unit system like `CLDR` you currently have to refer to at least one element like `CLDR.BYTE`. That's what `Unit test = BYTE;` does. Due to lazy loading, if you simply try to parse "bit" or "byte" without this they won't be recognized. We'll think of something to maybe explicitly do that, If you call e.g. the SPI or anything even just the name of unit systems available that should do the trick.

**Comment by zifnab87** [comment]
Oh thanks! I tried the code without changing anything in the associated libraries and I am getting: 

`Exception in thread "main" javax.measure.format.ParserException: tec.uom.se.internal.format.TokenException
	at tec.uom.se.format.EBNFUnitFormat.parse(EBNFUnitFormat.java:285)
	at tec.uom.se.format.EBNFUnitFormat.parse(EBNFUnitFormat.java:290)
	at tec.uom.se.AbstractUnit.parse(AbstractUnit.java:177)
	at testbed.TestBed.main(TestBed.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: tec.uom.se.internal.format.TokenException
	at tec.uom.se.internal.format.UnitFormatParser.atomicExpr(UnitFormatParser.java:326)
	at tec.uom.se.internal.format.UnitFormatParser.exponentExpr(UnitFormatParser.java:221)
	at tec.uom.se.internal.format.UnitFormatParser.mulExpr(UnitFormatParser.java:140)
	at tec.uom.se.internal.format.UnitFormatParser.addExpr(UnitFormatParser.java:107)
	at tec.uom.se.internal.format.UnitFormatParser.compoundExpr(UnitFormatParser.java:77)
	at tec.uom.se.internal.format.UnitFormatParser.parseUnit(UnitFormatParser.java:65)
	at tec.uom.se.format.EBNFUnitFormat.parse(EBNFUnitFormat.java:273)
	... 8 more
`
Do I need to get a new pom library or clone latest? thanks!

**Comment by keilw** [comment]
You're using uom-se, I see. Please use `1.0.3-SNAPSHOT`. Since you already reference systems.uom `0.6-SNAPSHOT` you should be able to do so with uom-se. The default format was EBNFUnitFormat, which was inconsistent with the RI, thus I changed it and you get those errors using the older build of uom-se.

**Comment by zifnab87** [comment]
No worries! Thank you!! I am now getting:

```
Exception in thread "main" javax.measure.format.ParserException: Parse Error
	at tec.uom.se.format.SimpleUnitFormat$DefaultFormat.check(SimpleUnitFormat.java:561)
	at tec.uom.se.format.SimpleUnitFormat$DefaultFormat.parseSingleUnit(SimpleUnitFormat.java:414)
	at tec.uom.se.format.SimpleUnitFormat$DefaultFormat.parseProductUnit(SimpleUnitFormat.java:425)
	at tec.uom.se.format.SimpleUnitFormat.parseObject(SimpleUnitFormat.java:269)
	at tec.uom.se.format.SimpleUnitFormat$DefaultFormat.parse(SimpleUnitFormat.java:765)
	at tec.uom.se.format.SimpleUnitFormat$DefaultFormat.parse(SimpleUnitFormat.java:760)
	at tec.uom.se.format.SimpleUnitFormat$DefaultFormat.parse(SimpleUnitFormat.java:751)
	at tec.uom.se.AbstractUnit.parse(AbstractUnit.java:177)
	at testbed.TestBed.main(TestBed.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

These are the libraries I am now running with:

`    <orderEntry type="library" name="Maven: tec.uom:uom-se:1.0.3-SNAPSHOT" level="project" />
    <orderEntry type="library" name="Maven: tec.uom.lib:uom-lib-common:1.0.1" level="project" />
    <orderEntry type="library" name="Maven: systems.uom:systems-common:0.6-SNAPSHOT" level="project" />
    <orderEntry type="library" name="Maven: tec.units:unit-ri:1.0.2-SNAPSHOT" level="project" />
    <orderEntry type="library" name="Maven: si.uom:si-quantity:0.6.3-SNAPSHOT" level="project" />
    <orderEntry type="library" name="Maven: si.uom:si-units:0.6.3-SNAPSHOT" level="project" />
    <orderEntry type="library" name="Maven: systems.uom:systems-quantity:0.6-SNAPSHOT" level="project" />
    <orderEntry type="library" name="Maven: systems.uom:systems-unicode:0.6-SNAPSHOT" level="project" />
    <orderEntry type="library" name="Maven: systems.uom:systems-parent:0.6-SNAPSHOT" level="project" />`
