### ISSUE TITLE
Formatting Length and some other quantities does not always work

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-systems#74]
The method TestUnitJacksonModule.testSerializeLength()  fails with
```
org.junit.ComparisonFailure: Expected JSON with a UCUM representation of the length unit expected:<"[km]"> but was:<"[m.1000]">
	at org.junit.Assert.assertEquals(Assert.java:115)
	at com.opower.unitsofmeasure.TestUnitJacksonModule.testSerializeLength(TestUnitJacksonModule.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

While "m.1000" is mathematically correct. it should be "km" see http://unitsofmeasure.org/ucum.html#section-Prefixes

**Comment by keilw** [comment]
Could be related to https://github.com/unitsofmeasurement/uom-systems/issues/64

**Comment by magnonasc** [comment]
In what project is this? I can't find that class

**Comment by keilw** [comment]
@magnonasc It is in https://github.com/unitsofmeasurement/jackson-module-unitsofmeasure which is based entirely on JUnit tests right now. It looks like formatting (and most likely parsing, too) work assuming you all use UCUM units. So `KILO(UCUM.METER)` works fine, `KILO(Units.METRE)` currently doesn't. I think it's acceptable for now to stay consistent within the UCUM space. Maybe there's even a solution similar to the only bundle right now `tec.uom.se.unit.Units.KILOMETRE_PER_HOUR`...? We can try that for other `Units `members.

**Comment by magnonasc** [comment]
This problem occurs to `Frequency` too, which makes your "possibly other quantities" true.

**Comment by keilw** [comment]
Is it similar, that the UCUM one works and the one in other systems doesn't?

**Comment by magnonasc** [comment]
Nop, I used `HERTZ`, which is a `UCUM` unit, and it didn't work

**Comment by magnonasc** [comment]
It didn't work with some other `UCUM` units either, which doesn't refer directly to a non-UCUM unit

**Comment by keilw** [comment]
That's interesting because it is defined in `Units`. For `METER` vs. `METRE` it is more understandable because the names differ.

**Comment by keilw** [comment]
And those UCUM units all have a resource bundle entry without possible spelling difference?

**Comment by magnonasc** [comment]
`HERTZ` and `ELECTRON_MASS`? I don't think so

**Comment by magnonasc** [comment]
The problem for this case is that `getBaseUnits()` is getting the **really, really** base units, for example:
```
HERTZ = 1/s;
KILOHERTZ = KILO(HERTZ);
```
but `KILOHERTZ.getBaseUnits()` returns `1/s` instead of `HERTZ * 1000`

**Comment by keilw** [comment]
No, at the moment `getBaseUnits()` of a `TransformedUnit` returns `parentUnit.getBaseUnits();`
This goes all the way back to JScience or JSR 275. The method had a different name, but it's always been specific to product units. In case of a `TransformedUnit` like `KILOHERTZ` the concrete class returns a `UnitConverter`. It's a different method and the converter could be different.

We could discuss treating it differently in a TransformedUnit, but it also had to work both in uom-se and the RI.

**Comment by magnonasc** [comment]
One of the problems with the formatter/parser is that it seems that the symbols of the metric prefixes are defined on it construction, and it should rely on the variant being used, did you think about it somewhere I can't see or is it a case that we need to fix?

**Comment by magnonasc** [comment]
Heey @keilw, if I try to parse `khz`, what should I receive? Should it return a `KILO(HERTZ)` or throw an exception?
What I'm asking is, does `parse` only work with the registered units?

I created some tests for #81 but maybe I wasn't considering it, and if your answer is "it should throw an exception", then the tests are wrong and I should work only on the method `format` and not `parse`

**Comment by keilw** [comment]
UCUMFormat seems different from EBNFUnitFormat on that, please compare the two, it works fine to parse "Hz" and "kHz" there (only case-sensitive in this case ;-)

**Comment by magnonasc** [comment]
And about the variant of the prefixes, does the api allow us to have multiple variants to that or do we need to create another class to hold the prefixes, like `UCUMMETRICPREFIX`?

**Comment by keilw** [comment]
No it must work with a single MetricPrefix per implementation. Actually just pushed UCUM system and bundles as well as demos. I must sleep now, have to catch a train at 6am, but it works similar to how KPH was already added to the UCUMFormat bundle. Feel free to tweak, e.g. most prefixes in CI variant might have to be upper-case only except special ones...

**Comment by magnonasc** [comment]
About your comment over `TransformedUnit.getBaseUnits()`, I was going to make a pull request but I had that end of line problem aswell, and as it was only one line I gave up.. But I'm pretty sure that this method should return `null` itself, as `getBaseUnits()` is created to `ProductUnit`, instead of that you should use (or delegate) the method `getParentUnit()`, which would replace the use of the other without any problem.
